/**
 *
 * $Id$
 */
package co.edu.uniandes.metamodel.Html.validation;


/**
 * A sample validator interface for {@link co.edu.uniandes.metamodel.Html.APPLET}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface APPLETValidator {
	boolean validate();

	boolean validateApplet(Object value);
	boolean validateClass(Object value);
	boolean validateSrc(Object value);
	boolean validateAlign(Object value);
	boolean validateWidth(Object value);
	boolean validateHeight(Object value);
}
