/**
 *
 * $Id$
 */
package co.edu.uniandes.metamodel.Html.validation;


/**
 * A sample validator interface for {@link co.edu.uniandes.metamodel.Html.OBJECT}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OBJECTValidator {
	boolean validate();

	boolean validateClassid(Object value);
	boolean validateId(Object value);
	boolean validateData(Object value);
	boolean validateType(Object value);
	boolean validateStandby(Object value);
}
