/**
 *
 * $Id$
 */
package co.edu.uniandes.metamodel.Html.validation;


/**
 * A sample validator interface for {@link co.edu.uniandes.metamodel.Html.TEXTAREA}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TEXTAREAValidator {
	boolean validate();

	boolean validateName(Object value);
	boolean validateRows(Object value);
	boolean validateCols(Object value);
}
